export const GET_PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const GET_PRODUCT_FAILURE = "PRODUCT_FAILURE";

export const GET_WOMENS_PRODUCT_REQUEST = "WOMENS_PRODUCT_REQUEST";
export const GET_WOMENS_PRODUCT_SUCCESS = "WOMENS_PRODUCT_SUCCESS";
export const GET_WOMENS_PRODUCT_FAILURE = "WOMENS_PRODUCT_FAILURE";
export const ADD_TO_CART = "ADD_TO_CART";